#!/usr/bin/env python3
"""Write the tool-using arm's frozen Codex profile, and say what each setting costs.

    python3 tools/arm_profile.py --out DIR [--shim-port 5098]

The arm's identity is not "Qwen with tools". It is **Qwen3.6-35B-A3B served locally, reached
through the Responses shim, driven by Codex CLI 0.146.1 under exactly this profile.** The ~20 KB
of Codex instructions and this tool inventory are a material treatment, so the profile is
generated by a committed program rather than typed by hand, and its SHA-256 belongs in the round
record next to the model's.

An isolated CODEX_HOME is not tidiness. The operator's own Codex config carries plugins, MCP
apps, goals, skills and a trusted-projects list, all of which would enter the party's prompt and
none of which the record could describe.

The settings that carry a cost
------------------------------
`sandbox_mode = "workspace-write"` rather than `"read-only"`. Network access is not grantable in
read-only mode, and a party that cannot fetch a URL cannot answer the question the arm exists to
ask. The load-bearing requirement was never "no writes anywhere" — it is **"a party asked whether
the record can be trusted must not be able to write to the record"** — and that survives: writes
are confined to the cwd, `writable_roots` is empty, and the cwd is a scratch directory outside
the repository. `tools/arm_acceptance.py` verifies it by effect, which is the only form of that
claim worth anything.

`web_search = "disabled"`. Codex's hosted search has no executor behind this endpoint. Leaving it
on would let the party believe it searched when nothing ran.

No MCP fetch tool. It is written and works, but Codex will not route calls into a namespace —
see `tools/fetch_tool_mcp.py`. Browsing is therefore `exec_command` plus the sandbox's network,
and the provenance is narrower for it: the exact command and the exact bytes returned, with no
content digest and no SSRF guard.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

CONFIG = """\
# OAGF tool-using arm — frozen profile, generated by tools/arm_profile.py. Do not hand-edit:
# the round record cites this file's SHA-256, and a local edit would make that citation false.

model = "{model}"
model_provider = "oagf"
approval_policy = "never"

# No hosted search: nothing behind this endpoint executes it, and an unbacked tool invites the
# party to believe it searched when nothing ran.
web_search = "disabled"

# workspace-write, NOT read-only. Network access is only grantable in this mode, and without it
# the party cannot resolve a citation -- the one capability this arm exists to provide. Writes
# stay inside the cwd, which is a scratch directory outside the repository.
sandbox_mode = "workspace-write"

[sandbox_workspace_write]
network_access = true
writable_roots = []
exclude_slash_tmp = false

[model_providers.oagf]
name = "oagf"
base_url = "http://127.0.0.1:{shim_port}/v1"
wire_api = "responses"
requires_openai_auth = false

# Everything below narrows the tool profile. Each of these otherwise reaches the party as a tool
# it cannot use, or as instruction text the record cannot describe.
[features]
multi_agent = false
multi_agent_v2 = false
enable_mcp_apps = false
goals = false
skills = false
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", required=True, help="directory to use as CODEX_HOME")
    parser.add_argument("--shim-port", type=int, default=5098)
    parser.add_argument("--model", default="qwen3.6-35b-a3b")
    args = parser.parse_args()

    out = Path(args.out).resolve()
    out.mkdir(parents=True, exist_ok=True)
    config = CONFIG.format(model=args.model, shim_port=args.shim_port)
    path = out / "config.toml"
    path.write_text(config, encoding="utf-8")

    digest = hashlib.sha256(config.encode("utf-8")).hexdigest()
    print(f"wrote {path}")
    print(f"profile sha256 {digest}")
    print(f"\nCODEX_HOME={out} codex exec --cd <scratch-cwd> --skip-git-repo-check '<prompt>'")
    print("\nBefore any sample, run tools/arm_acceptance.py against this exact profile.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
