#!/usr/bin/env python3
"""Generate the deficiency register views from the structured artifact.

    python3 tools/build_register_view.py

Writes three files, all derived, none hand-edited:

    corpus/deficiency-register.md   metadata table for GitHub readers
    docs/deficiencies.html          the self-contained public view
    docs/deficiencies.md            plain-text mirror of the register itself

`corpus/deficiencies.md` remains **canonical**. These are annotation over it and
never replace it: the view carries classification and counts, and sends the
reader to the prose for what actually happened.

The plain-text mirror exists because this corpus has evidence that agents cannot
read the alternatives. Gemini's round-01 environment could reach neither
`raw.githubusercontent.com` nor the `/blob/` UI, which renders via JavaScript and
returns a navigation shell to automated readers. GitHub Pages serves any file at
a predictable path from the same origin as the page, so the mirror is reachable
where those two are not.

Every number on these pages is computed from the artifact. None is typed. The
count this repository published for months was typed, and it was wrong in three
different places at once.

Deterministic: no clock, no randomness, sorted throughout.
"""

from __future__ import annotations

import html
import json
import shutil
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ARTIFACT = REPO_ROOT / "corpus/artifacts/deficiency-register.json"
REGISTER = REPO_ROOT / "corpus/deficiencies.md"

ACTOR_LABEL = {
    "actor_human_operator": "human operator",
    "actor_repository_annotator_invocation": "the annotator",
    "actor_designated_review_round_invocation": "a designated review round",
    "actor_external_adversarial_reviewer": "an external reviewer",
    "actor_other_contributor_invocation": "another contributor",
}
EVIDENCE_LABEL = {
    "origin_supported_by_preserved_artifact": "preserved artifact",
    "origin_supported_by_git_history_only": "git history only",
    "origin_asserted_in_register_only": "asserted in the register only",
    "origin_disputed": "disputed",
}
REPAIR_LABEL = {
    "affected_object_fully_repairable_by_supersession": "repairable by supersession",
    "affected_object_partially_repairable_by_supersession": "partly repairable",
    "affected_measurement_repairable_only_by_rerun": "only by re-running the measurement",
    "affected_object_repairable_only_if_missing_evidence_recovered": "only if missing evidence is recovered",
    "affected_object_not_repairable": "not repairable",
    "affected_object_repairability_not_applicable": "not applicable",
}
REMEDIATION_LABEL = {
    "remediation_not_started": "not started",
    "remediation_partially_applied": "partly applied",
    "remediation_applied_not_verified": "applied, not verified",
    "remediation_verified": "verified",
    "remediation_impossible_for_affected_object": "impossible",
}
CONTROL_LABEL = {
    "prospective_control_not_required": "not required",
    "prospective_control_required_not_implemented": "required, not implemented",
    "prospective_control_implemented_not_validated": "implemented, not validated",
    "prospective_control_validated": "validated",
}
CONTROL_CLASS = {
    "prospective_control_not_required": "",
    "prospective_control_required_not_implemented": "d",
    "prospective_control_implemented_not_validated": "w",
    "prospective_control_validated": "g",
}
REMEDIATION_CLASS = {
    "remediation_not_started": "d",
    "remediation_partially_applied": "w",
    "remediation_applied_not_verified": "w",
    "remediation_verified": "g",
    "remediation_impossible_for_affected_object": "d",
}


def num(entry_id: str) -> int:
    return int(entry_id.split("-")[1])


def load() -> dict:
    return json.loads(ARTIFACT.read_text(encoding="utf-8"))


# --------------------------------------------------------------------------- md
def render_markdown(doc: dict) -> str:
    entries = sorted(doc["entries"], key=lambda e: num(e["id"]))
    by_actor = Counter(e["first_articulation"]["actor_context"] for e in entries)
    by_control = Counter(e["prospective_control"]["state"] for e in entries)
    review = Counter(e["human_review"]["status"] for e in entries)
    rows = sum(len(e["affected_objects"]) for e in entries)

    out = [
        "# Deficiency register — classification\n\n",
        "**Generated** by `tools/build_register_view.py` from "
        "`corpus/artifacts/deficiency-register.json`. Do not edit this file; edit the artifact.\n\n",
        "[`corpus/deficiencies.md`](deficiencies.md) is **canonical**. This is metadata over it, "
        "and it carries no detail about what any defect actually was — follow the links.\n\n",
        "---\n\n## What this classification does and does not establish\n\n",
        "It records, per entry, where the defect was **first substantively articulated in preserved "
        "material**, what it affects, whether each affected object is repairable, and whether a "
        "forward control exists and has been validated.\n\n",
        "It does **not** establish that any of those judgements is correct. They were made by the "
        "annotator, which is a party to the record. `tools/check_register.py` verifies structure, "
        "one-to-one coverage, vocabulary, and that each entry's prose has not changed since it was "
        "classified. **It never verifies meaning**, and a deterministic rule that claimed to would "
        "be D-25 over again.\n\n",
        f"**{review.get('reviewed_by_custodian', 0)} of {len(entries)}** classifications have been "
        "read by a human against the prose.\n\n",
        "On attribution: this project cannot observe who first *privately noticed* a defect, so it "
        "records where one was first *written down*, with an evidence class. A question that "
        "prompted an investigation is recorded as a **trigger**, not as the finding.\n\n",
        "---\n\n## Counts\n\n### First substantive articulation\n\n| Where | Entries |\n|---|---|\n",
    ]
    for actor, count in sorted(by_actor.items(), key=lambda kv: -kv[1]):
        out.append(f"| {ACTOR_LABEL[actor]} | {count} |\n")

    reviewer_found = sorted(
        (e["id"] for e in entries
         if e["first_articulation"]["actor_context"] == "actor_designated_review_round_invocation"),
        key=num)
    if reviewer_found:
        out.append(
            f"\n**{len(reviewer_found)} entries — {reviewer_found[0]} through {reviewer_found[-1]} — "
            "were first substantively articulated in preserved designated review-round submissions.** "
            "That is narrower than \"found by the reviewers\", and unlike it, checkable.\n")

    out.append("\n### Prospective control\n\n| State | Entries |\n|---|---|\n")
    for state in CONTROL_LABEL:
        if by_control.get(state):
            out.append(f"| {CONTROL_LABEL[state]} | {by_control[state]} |\n")

    out.extend([
        f"\n### Affected objects\n\n**{rows} affected-object rows across {len(entries)} entries.** "
        "Repairability is recorded per object because it is not a property of a deficiency: D-09's "
        "raw transcript is not repairable while its `segments.json` annotation was corrected, and a "
        "single yes/no is false for one of them whichever way it is written.\n\n",
        "---\n\n## Entries\n\n",
    ])

    for e in entries:
        fa = e["first_articulation"]
        out.append(f"### {e['id']} — {e['title']}\n\n")
        out.append(f"[Full entry](deficiencies.md#{anchor(e)})\n\n")
        out.append(f"- **First articulated:** {ACTOR_LABEL[fa['actor_context']]}")
        if fa.get("actor_label"):
            out.append(f" — {fa['actor_label']}")
        out.append(f", {fa['date_utc']} · evidence: *{EVIDENCE_LABEL[fa['evidence_class']]}*\n")
        out.append(f"  - where: `{fa['where']}`\n")
        if "investigation_triggered_by" in e:
            t = e["investigation_triggered_by"]
            label = t.get("actor_label") or ACTOR_LABEL[t["actor_context"]]
            out.append(f"- **Triggered by** {label}: {t['what']}\n")
        for n in e.get("narrowed_or_corrected_by", []):
            out.append(f"- **Narrowed/corrected** by {n['actor_label']} ({n['round']}): {n['what']}\n")
        out.append(f"- **Prospective control:** {CONTROL_LABEL[e['prospective_control']['state']]}")
        if e["prospective_control"].get("mechanism"):
            out.append(f" — {e['prospective_control']['mechanism']}")
        out.append("\n")
        if "remediation_effort" in e:
            r = e["remediation_effort"]
            out.append(f"- **Effort:** {r['estimate'].replace('remediation_effort_', '')} — {r['basis']}\n")
        for claim in e.get("invalidates", []):
            out.append(f"- **Invalidates:** {claim}\n")
        out.append(f"- **Human review:** {e['human_review']['status']}\n")
        out.append("\n| Affected object | Repairable? | Remediation |\n|---|---|---|\n")
        for o in e["affected_objects"]:
            note = f" <br><sub>{o['note']}</sub>" if o.get("note") else ""
            out.append(f"| {o['object']}{note} | {REPAIR_LABEL[o['repairability']]} "
                       f"| {REMEDIATION_LABEL[o['remediation_state']]} |\n")
        out.append("\n")

    return "".join(out)


def anchor(entry: dict) -> str:
    """GitHub's heading anchor for this entry's markdown heading."""
    text = f"{entry['id']} — {entry['title']}".lower()
    keep = [c if (c.isalnum() or c in " -") else "" for c in text]
    return "".join(keep).strip().replace(" ", "-")


# ------------------------------------------------------------------------- html
CSS = """
:root{--bg:#fbfaf8;--fg:#1a1a1a;--mut:#6b6b6b;--line:#e2ded8;--card:#fff;--accent:#7a5c3e;
--warn:#8a5a00;--bad:#9b2c2c;--ok:#2f6b4f;--code:#f4f1ec}
@media(prefers-color-scheme:dark){:root{--bg:#161514;--fg:#e8e4de;--mut:#9a948c;--line:#33302c;
--card:#1e1c1a;--accent:#c9a678;--warn:#d9a441;--bad:#e07a7a;--ok:#7ab894;--code:#242220}}
:root[data-theme=dark]{--bg:#161514;--fg:#e8e4de;--mut:#9a948c;--line:#33302c;--card:#1e1c1a;
--accent:#c9a678;--warn:#d9a441;--bad:#e07a7a;--ok:#7ab894;--code:#242220}
:root[data-theme=light]{--bg:#fbfaf8;--fg:#1a1a1a;--mut:#6b6b6b;--line:#e2ded8;--card:#fff;
--accent:#7a5c3e;--warn:#8a5a00;--bad:#9b2c2c;--ok:#2f6b4f;--code:#f4f1ec}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
font:15px/1.6 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
header{border-bottom:1px solid var(--line);padding:.8rem 1rem;position:sticky;top:0;background:var(--bg);z-index:5}
.hrow{max-width:1000px;margin:0 auto;display:flex;gap:.7rem;align-items:baseline;flex-wrap:wrap}
h1{font-size:1rem;margin:0;font-weight:650}
h1 small{display:block;font-weight:400;color:var(--mut);font-size:.75rem}
nav a{color:var(--accent);font-size:.82rem;margin-right:.8rem}
main{max-width:1000px;margin:0 auto;padding:1rem}
h2{font-size:1.05rem;margin:2rem 0 .6rem;padding-bottom:.3rem;border-bottom:2px solid var(--line)}
table{border-collapse:collapse;width:100%;margin:.6rem 0;font-size:.86rem}
th,td{border:1px solid var(--line);padding:.35rem .5rem;text-align:left;vertical-align:top}
th{background:var(--code);font-weight:600}
.wrap{overflow-x:auto}
.lede{border-left:3px solid var(--accent);padding:.5rem .9rem;background:var(--code);
border-radius:0 6px 6px 0;margin:1rem 0;font-size:.9rem}
.limit{border-left:3px solid var(--bad)}
.e{background:var(--card);border:1px solid var(--line);border-radius:8px;margin:.7rem 0;padding:.7rem .9rem}
.e h3{margin:0 0 .35rem;font-size:.95rem}
.e h3 a{color:inherit;text-decoration:none}
.e h3 a:hover{color:var(--accent)}
.tag{font-size:.68rem;padding:.1rem .45rem;border-radius:99px;border:1px solid var(--line);
color:var(--mut);white-space:nowrap;margin-left:.3rem;display:inline-block}
.tag.d{border-color:var(--bad);color:var(--bad)}
.tag.w{border-color:var(--warn);color:var(--warn)}
.tag.g{border-color:var(--ok);color:var(--ok)}
.meta{font-size:.82rem;color:var(--mut);margin:.3rem 0}
.meta b{color:var(--fg);font-weight:600}
.bar{display:flex;gap:.4rem;flex-wrap:wrap;margin:.8rem 0;align-items:center}
.bar .lbl{font-size:.72rem;text-transform:uppercase;letter-spacing:.06em;color:var(--mut)}
button{padding:.3rem .55rem;border:1px solid var(--line);border-radius:6px;background:var(--card);
color:var(--fg);font:inherit;font-size:.78rem;cursor:pointer}
button:hover{border-color:var(--accent)}
button[aria-pressed=true]{background:var(--accent);color:var(--bg);border-color:var(--accent)}
.hidden{display:none!important}
footer{max-width:1000px;margin:2rem auto;padding:1rem;border-top:1px solid var(--line);
color:var(--mut);font-size:.78rem}
a{color:var(--accent)}
code{background:var(--code);padding:.05rem .3rem;border-radius:3px;font-size:.92em;word-break:break-all}
"""

JS = r"""
const $$=s=>[...document.querySelectorAll(s)];
let f={actor:new Set(),control:new Set()};
function apply(){
  let n=0;
  for(const el of $$('.e')){
    const ok=(!f.actor.size||f.actor.has(el.dataset.actor))
          && (!f.control.size||f.control.has(el.dataset.control));
    el.classList.toggle('hidden',!ok); if(ok)n++;
  }
  document.getElementById('count').textContent=n+' of '+$$('.e').length+' entries';
}
document.addEventListener('DOMContentLoaded',()=>{
  $$('[data-f]').forEach(b=>b.addEventListener('click',()=>{
    const s=f[b.dataset.f], v=b.dataset.v;
    s.has(v)?s.delete(v):s.add(v);
    b.setAttribute('aria-pressed',s.has(v)); apply();
  }));
  document.getElementById('theme').addEventListener('click',()=>{
    const cur=document.documentElement.getAttribute('data-theme');
    const next=cur==='dark'?'light':cur==='light'?'':'dark';
    next?document.documentElement.setAttribute('data-theme',next)
        :document.documentElement.removeAttribute('data-theme');
    document.getElementById('theme').textContent=next||'auto';
  });
  apply();
});
"""


def render_html(doc: dict, subset: list[dict] | None = None,
                pager: str = "", title_suffix: str = "") -> str:
    e_ = html.escape
    entries = subset if subset is not None else sorted(doc["entries"], key=lambda x: num(x["id"]))
    # Counters describe the WHOLE register, not this page's slice. A per-page count
    # would give four pages four different totals for the same register -- which is
    # the exact defect the register was already caught committing when three
    # artifacts of this repository stated three different counts of its own defects.
    every = sorted(doc["entries"], key=lambda x: num(x["id"]))
    by_actor = Counter(x["first_articulation"]["actor_context"] for x in every)
    by_control = Counter(x["prospective_control"]["state"] for x in every)
    by_evidence = Counter(x["first_articulation"]["evidence_class"] for x in every)
    reviewed = sum(1 for x in every
                   if x["human_review"]["status"] == "reviewed_by_custodian")
    rows = sum(len(x["affected_objects"]) for x in every)
    reviewer = sorted((x["id"] for x in every
                       if x["first_articulation"]["actor_context"]
                       == "actor_designated_review_round_invocation"), key=num)

    body = []
    for x in entries:
        fa = x["first_articulation"]
        control = x["prospective_control"]
        tags = [f'<span class="tag {CONTROL_CLASS[control["state"]]}">'
                f'{e_(CONTROL_LABEL[control["state"]])}</span>']
        if fa["evidence_class"] != "origin_supported_by_preserved_artifact":
            tags.append(f'<span class="tag w">{e_(EVIDENCE_LABEL[fa["evidence_class"]])}</span>')
        if x["human_review"]["status"] == "not_reviewed":
            tags.append('<span class="tag d">classification not human-reviewed</span>')

        parts = [
            f'<h3><a href="artifacts/deficiencies.md">{e_(x["id"])} — {e_(x["title"])}</a>{"".join(tags)}</h3>'
        ]
        who = ACTOR_LABEL[fa["actor_context"]]
        if fa.get("actor_label"):
            who += f' — {fa["actor_label"]}'
        parts.append(f'<p class="meta"><b>First articulated:</b> {e_(who)}, {e_(fa["date_utc"])} '
                     f'· <code>{e_(fa["where"])}</code></p>')
        if "investigation_triggered_by" in x:
            t = x["investigation_triggered_by"]
            label = t.get("actor_label") or ACTOR_LABEL[t["actor_context"]]
            parts.append(f'<p class="meta"><b>Triggered by</b> {e_(label)} — {e_(t["what"])} '
                         f'<em>A trigger is not the finding.</em></p>')
        for n in x.get("narrowed_or_corrected_by", []):
            parts.append(f'<p class="meta"><b>Narrowed by</b> {e_(n["actor_label"])} '
                         f'({e_(n["round"])}) — {e_(n["what"])}</p>')
        if control.get("mechanism"):
            parts.append(f'<p class="meta"><b>Forward control:</b> {e_(control["mechanism"])}</p>')
        for claim in x.get("invalidates", []):
            parts.append(f'<p class="meta"><b>Invalidates:</b> {e_(claim)}</p>')

        obj_rows = "".join(
            f'<tr><td>{e_(o["object"])}'
            + (f'<br><small>{e_(o["note"])}</small>' if o.get("note") else "")
            + f'</td><td>{e_(REPAIR_LABEL[o["repairability"]])}</td>'
            f'<td><span class="tag {REMEDIATION_CLASS[o["remediation_state"]]}">'
            f'{e_(REMEDIATION_LABEL[o["remediation_state"]])}</span></td></tr>'
            for o in x["affected_objects"])
        parts.append('<div class="wrap"><table><tr><th>Affected object</th><th>Repairable?</th>'
                     f'<th>Remediation</th></tr>{obj_rows}</table></div>')

        body.append(f'<article class="e" data-actor="{e_(fa["actor_context"])}" '
                    f'data-control="{e_(control["state"])}">{"".join(parts)}</article>')

    def btn(kind, value, label):
        return (f'<button data-f="{kind}" data-v="{e_(value)}" aria-pressed="false">'
                f'{e_(label)}</button>')

    actor_btns = "".join(btn("actor", a, f"{ACTOR_LABEL[a]} ({c})")
                         for a, c in sorted(by_actor.items(), key=lambda kv: -kv[1]))
    control_btns = "".join(btn("control", s, f"{CONTROL_LABEL[s]} ({by_control[s]})")
                           for s in CONTROL_LABEL if by_control.get(s))

    evidence_rows = "".join(
        f"<tr><td>{e_(EVIDENCE_LABEL[k])}</td><td>{v}</td></tr>"
        for k, v in sorted(by_evidence.items(), key=lambda kv: -kv[1]))

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Deficiency register — Open ASI Governance Forum</title>
<meta name="description" content="Every known defect in the OAGF record, its instruments and its tooling: what it affects, whether each affected object is repairable, and whether a forward control exists and has been validated.">
<link rel="alternate" type="text/markdown" href="artifacts/deficiencies.md">
<style>{CSS}</style>
</head>
<body>
<header><div class="hrow">
<h1>Deficiency register<small>{len(entries)} entries · classification is annotation, not testimony</small></h1>
<nav><a href="index.html">threaded record</a><a href="artifacts/deficiencies.md">register as plain text</a>
<a href="https://github.com/open-asi-governance/open-asi-governance-forum">source</a></nav>
<button id="theme" style="margin-left:auto">auto</button>
</div></header>
<main>

<div class="lede"><strong>This page carries classification, not content.</strong> What each defect
actually was is in the register itself — <a href="artifacts/deficiencies.md">plain text, same origin</a>, which
is served here because this corpus has evidence that agents cannot read the alternatives: a reviewer's
environment in round 01 could reach neither the raw CDN nor GitHub's <code>/blob/</code> UI.</div>

<div class="lede limit"><strong>What this does not establish.</strong> Every judgement below was made
by the annotator, which is <em>a party to the record it classifies</em>. The build verifies structure,
one-to-one coverage, controlled vocabulary, and that an entry's prose has not changed since it was
classified — it <strong>never verifies meaning</strong>, because no deterministic rule can, and one
claiming to would be D-25 over again. <strong>{reviewed} of {len(entries)}</strong> classifications
have been read by a human against the prose.</div>

<h2>Where defects were first written down</h2>
<p class="meta">This project cannot observe who first <em>privately noticed</em> a defect, so it
records where one was first substantively <em>articulated in preserved material</em>, and how strong
that evidence is. A question that prompted an investigation is a <strong>trigger</strong>, not a
finding — which is why the operator's "why was 0.7 chosen?" appears against D-26 and D-28 as a
trigger rather than as their origin.</p>
<div class="wrap"><table><tr><th>Origin evidence</th><th>Entries</th></tr>{evidence_rows}</table></div>
<p class="meta">{"<strong>" + str(len(reviewer)) + " entries — " + reviewer[0] + " through " + reviewer[-1] + " — were first substantively articulated in preserved designated review-round submissions.</strong> That is narrower than “found by the reviewers”, and unlike it, it is checkable against committed artifacts." if reviewer else ""}</p>

<h2>Forward controls</h2>
<p class="meta">Whether a control exists to stop recurrence, and whether it has been
<em>validated</em> rather than merely written down. D-29's lesson, filed after a hash anchor turned
out never to have been checked by the path that runs: <strong>a check that is available is not a
check that runs.</strong></p>

<h2>{rows} affected-object rows across {len(entries)} entries</h2>
<p class="meta">Repairability is recorded <strong>per affected object</strong>, because it is not a
property of a deficiency. D-09 is the proof: the raw transcript's merged identities are
<em>not repairable</em>, while its <code>segments.json</code> annotation <em>was corrected</em>. A
single yes/no is false for one of them whichever way it is written — and the register's own prose
table, which had exactly one column, misstated entries for that reason.</p>

<div class="bar"><span class="lbl">first articulated</span>{actor_btns}</div>
<div class="bar"><span class="lbl">forward control</span>{control_btns}
<span class="meta" id="count" style="margin-left:auto"></span></div>

{pager}
{"".join(body)}
{pager}
</main>
<footer>
<p>Generated by <code>tools/build_register_view.py</code> from
<code>corpus/artifacts/deficiency-register.json</code>, which is annotation over
<code>corpus/deficiencies.md</code>. The markdown is canonical. Every number here is computed from
the artifact; none is typed. The count this repository published for months <em>was</em> typed, and
it was wrong in three places at once — 21 on the site, 24 in the register's own header, 28 headings
in the file.</p>
<p>Classification authored by Claude Code (Anthropic), a party to the record it classifies. Custodian:
Stephen Reed. Corpus CC BY 4.0; code Apache-2.0. Reading, quoting and ingestion are permitted under
those terms.</p>
</footer>
<script>{JS}</script>
</body>
</html>
"""


def main() -> int:
    if not ARTIFACT.is_file():
        print(f"missing {ARTIFACT.relative_to(REPO_ROOT)}")
        return 1
    doc = load()

    md_out = REPO_ROOT / "corpus/deficiency-register.md"
    md_out.write_text(render_markdown(doc), encoding="utf-8")

    docs = REPO_ROOT / "docs"
    docs.mkdir(parents=True, exist_ok=True)

    # CHUNKED, for the same reason the viewer is. The register grew from ~14,300 to
    # ~19,000 estimated tokens in six commits on 2026-08-06 -- roughly 600-1,100 per
    # entry filed -- and crossed the ceiling while nothing was watching. Packing by
    # measured size rather than a fixed entry count means the next twenty entries
    # split themselves instead of quietly exceeding the budget again.
    entries = sorted(doc["entries"], key=lambda x: num(x["id"]))
    CHROME, PER_TOKEN, PACK_TO = 24_000, 3.4, 15_000
    chunks, current, size = [], [], 0
    for entry in entries:
        cost = len(json.dumps(entry)) * 2          # prose renders larger than its JSON
        if current and (CHROME + size + cost) / PER_TOKEN > PACK_TO:
            chunks.append(current)
            current, size = [], 0
        current.append(entry)
        size += cost
    if current:
        chunks.append(current)

    def slug_for(index):
        return "deficiencies.html" if index == 0 else f"deficiencies-{index + 1}.html"

    written = []
    for index, chunk in enumerate(chunks):
        links = []
        for other, group in enumerate(chunks):
            label = f"{group[0]['id']}–{group[-1]['id']}"
            links.append(f'<a href="{slug_for(other)}"'
                         f'{" aria-current=\"page\"" if other == index else ""}>{label}</a>')
        pager = f'<nav class="pager">{"".join(links)}</nav>'
        suffix = "" if len(chunks) == 1 else f" ({chunk[0]['id']}–{chunk[-1]['id']})"
        page = render_html(doc, subset=chunk, pager=pager, title_suffix=suffix)
        out = docs / slug_for(index)
        out.write_text(page, encoding="utf-8")
        written.append(out)
    html_out = written[0]

    # THE EXACT ARTIFACT IS A DOWNLOAD, NOT A PAGE, and the distinction is recorded
    # rather than assumed. T-03 requires both "every corpus document reachable as
    # plain text" and "no single page exceeds ~20,000 tokens". The register is
    # ~29,600 estimated tokens, so those two requirements conflict for this file --
    # and for the 107,000-character founding transcript behind it.
    #
    # Resolution: the WHOLE file is served byte-identically under docs/artifacts/,
    # because an agent verifying a SHA-256 needs the whole file and a slice of it is
    # useless for that. It is exempt from the page ceiling by name in
    # tools/check_page_budget.py, and it is linked as a download. The READABLE
    # surface is the chunked HTML, which is under budget.
    #
    # This is a custodian-level reading of a requirement that does not resolve
    # itself. It is written here so that if the reading is wrong, it is wrong
    # visibly rather than by a glob nobody notices.
    artifacts = docs / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)
    mirror = artifacts / "deficiencies.md"
    shutil.copyfile(REGISTER, mirror)

    stale = docs / "deficiencies.md"
    if stale.exists():
        stale.unlink()

    for path in (md_out, html_out, mirror):
        print(f"wrote {path.relative_to(REPO_ROOT)} — {path.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
